# Build a client and server using the student's files

# The executables will have the suffix .exe
EXESUFFIX = exe

# Names for building the client:
CLIENT_MAIN     = client
CLIENT_CXX      = requests client
CLIENT_COMMON   = MNIST_Image Node Layer NeuralNetwork 
CLIENT_PROVIDED = 


# Names for building the server
SERVER_MAIN     = 	server
SERVER_CXX      = 	responses parsing 
SERVER_COMMON   =   server my_pool Node Layer NeuralNetwork 
SERVER_PROVIDED =  



# Names for building the benchmark executable
# BENCH_MAIN   = bench
# BENCH_CXX    = bench

# NB: This Makefile does not add extra CXXFLAGS

# Pull in the common build rules
include common.mk